version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"  # Maps host port 5433 to the container's 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db  # For local testing, use the service name "db"
      POSTGRES_PORT: ${POSTGRES_PORT}  # Typically 5432
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
