version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"  # Maps host port 5433 to container's 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      OLLAMA_URL: http://ollama:11434  # Add Ollama URL to easily call it from web
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama  # Make sure web waits for ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"  # Expose Ollama API
    volumes:
      - ollama_data:/root/.ollama  # Persist models
    restart: unless-stopped
    # Optional: automatically pull llama3 model when container starts
    entrypoint: ["/bin/sh", "-c", "ollama pull llama3.2 && ollama serve"]

# Optional: You can uncomment pgAdmin if needed later
#  pgadmin:
#    image: dpage/pgadmin4:latest
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#    ports:
#      - "5050:80"
#    depends_on:
#      - db

volumes:
  postgres_data:
  ollama_data:
